### ISSUE TITLE
Issues in exercise 6 and 7

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#14]
In exercise 6 : Error occurs while running the notebook anomaly detection  
importing statsmodels v 0.8.0 
![image](https://user-images.githubusercontent.com/55180169/79722554-e2b5e980-8301-11ea-866e-89a2f6132b01.png)
Resolution: It shows the error but after that if you run the next command it shows statsmodel is installed with v0.9.0

Cmd 7: set_random_seed is not a method in tensorflow 2.0, it was before. 
![image](https://user-images.githubusercontent.com/55180169/79722578-ef3a4200-8301-11ea-93c4-31902df4af3b.png)
![image](https://user-images.githubusercontent.com/55180169/79722640-0bd67a00-8302-11ea-94a7-94941de1654a.png)
Resolution: Change in command 7 line 15 to “import tensorflow as tf” and in cmd 19 line 2 change the code to “tf.random.set_seed(10)”. It’ll work.

Exercise 7:
After running PumpFailurePrediction.cs, an error occurs that doesn’t output the log statements of the devices ,because of this error deployment of functions app also fails 
![image](https://user-images.githubusercontent.com/55180169/79722359-8b177e00-8301-11ea-8233-a34dc594b124.png)

Resolution:
The .NET version in the  code provided is 2.x whereas while creating the function app, it only takes   .NET version as 3.x

**Comment by DawnmarieDesJardins** [comment]
@srushti-714 @joelhulen @timahenning 
Thank you for bringing this to our attention.  We've scheduled a test/fix for this workshop and we'll address your issue in the review.

**Comment by joelhulen** [comment]
Working on it now :)
