### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by DJuanes** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#18]
The documentation is out of date.
The workshop cannot be followed because the IoT Central service has completely changed.

**Comment by DawnmarieDesJardins** [comment]
@DJuanes 
Thank you for bringing this to our attention.  The workshop is scheduled to retire November 30th and will be pulled from our library.  Apologies for any inconvenience.

**Comment by joelhulen** [comment]
@DawnmarieDesJardins, these issues may go beyond a regular test/fix cycle. @codingbandit, can you please review what needs to be updated WRT IoT Central?

**Comment by codingbandit** [comment]
As mentioned in this issue, since this lab was written IoT Central has undergone considerable changes. Even Microsoft Flow is now Power Automate. I have informed @timahenning  of my observations.

**Comment by DawnmarieDesJardins** [comment]
Hello @DJuanes !  I wanted to let you know we've scheduled an update for the workshop to bring it up to date. Please check back at the end of the month for the new material.  You'll know when it's complete by the date on the ReadMe page and inside the documents.  Again, thank you for bringing this to our attention.
