### ISSUE TITLE
Exercise 2 Task3 Issue

### ISSUE THREAD

**Issue by mpram** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#20]
Hi Team,
Any idea why the code is generating this issue and not able  to register the devices? Please see the screen below 
![Ex2Task3](https://user-images.githubusercontent.com/43581413/110395804-d5e6d500-803c-11eb-9664-307db3f396ec.png)

**Comment by codingbandit** [comment]
Hi @mpram - I'm sorry you've experienced some trouble, I started this lab from the beginning up to this step and unfortunately was not able to reproduce the issue. I recommend ensuring the appsettings.json file has and accurate SAS token and that the ID Scope value is correct. Let me know if this solves your issue. 

![image](https://user-images.githubusercontent.com/3979478/110403218-b8b90300-804a-11eb-9e7c-97b917e2bc77.png)

**Comment by codingbandit** [comment]
@mpram - looking at your screenshot more closely, it looks as if you don't have the latest source code. Please download the latest source code. The code for PumpDevice.cs on line 57 now looks like this:

![image](https://user-images.githubusercontent.com/3979478/110403542-41d03a00-804b-11eb-9896-0c0918635904.png)

**Comment by mpram** [comment]
Hi @codingbandit 

I think the latest code is not in github because I downloaded today and there was some discrepencancies between the prtscrn and Vs Code, I am planning to deliver this workshop for 100 attendees. I have a correct SAS Token and Scope ID.
Thanks for your quick response!

**Comment by codingbandit** [comment]
Hi @mpram - I'm at a loss at what else to recommend - if you navigate to the PumpDevice.cs  in this repository, it shows the code that was updated 2 months ago. Device connection strings are no longer being used, the code uses DPS. Link to the source file:  https://github.com/microsoft/MCW-Predictive-Maintenance-for-remote-field-devices/blob/master/Hands-on%20lab/Resources/FieldDeviceSimulator/Fabrikam.FieldDevice.Generator/PumpDevice.cs

![image](https://user-images.githubusercontent.com/3979478/110493909-0f612400-80c1-11eb-9cee-d5e222d4508d.png)

**Comment by mpram** [comment]
@codingbandit I downloaded all over again, I was checking the files you show above also, now is all working, just closing this one, I will continue with the rest . THANKS for the quick response!
