### ISSUE TITLE
June 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#21]

**Comment by codingbandit** [comment]
I welcome suggestions from the team. Here is my initial update suggestions:
- Review lab for correctness (technical, grammar, spelling)
- Update lab screenshots with changes in UI
- Update lab steps that need to be clarified/updated
- Create new architecture graphics with updated product naming (ex. Power Automate vs. Flow)
- Update code artifact NuGet packages, target .Net 5 wherever possible

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #22
