### ISSUE TITLE
Lab Guide Updates

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#23]
1. [Exercise 7, task 4 Step 4](https://github.com/Kalyani7744/MCW-Predictive-Maintenance-for-remote-field-devices/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Predictive%20Maintenance%20for%20remote%20field%20devices.md#task-4-create-notification-service-in-microsoft-power-automate): While configuring the flow,  it is mentioned to select the trigger **When there are messages in a queue** which is now updated to **When there are messages in a queue (V2) (preview)** as shown below. 

Both Screenshot and instruction has to be updated.

![LAB71](https://user-images.githubusercontent.com/83349665/125245347-149fdb00-e30e-11eb-8729-b710c535d02f.png)

2.  [Exercise 7, task 4 Step 5](https://github.com/Kalyani7744/MCW-Predictive-Maintenance-for-remote-field-devices/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Predictive%20Maintenance%20for%20remote%20field%20devices.md#task-4-create-notification-service-in-microsoft-power-automate) : While configuring the Azure Queue, Instead of **Connection Name** the user have to set **Authentication Type**  as **Access key** along with **Storage Account Name** and **Shared Storage Key** as shown in the below screenshot. 

Both instruction and screenshot has to be updated.

![LAB72](https://user-images.githubusercontent.com/83349665/125255886-83cefc80-e319-11eb-996f-85dcc097bd58.png)

3.  [Exercise 7, task 4 Step 6](https://github.com/Kalyani7744/MCW-Predictive-Maintenance-for-remote-field-devices/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Predictive%20Maintenance%20for%20remote%20field%20devices.md#task-4-create-notification-service-in-microsoft-power-automate): While Configuring the Queue, user have to select the **Storage account name** along with **Queue Name** as shown below. 

Both Instruction and screenshot has to be updated.

![LAB73](https://user-images.githubusercontent.com/83349665/125255968-977a6300-e319-11eb-8ea6-5ff215da8173.png)

4.  [Exercise 7, task 4 Step 10](https://github.com/Kalyani7744/MCW-Predictive-Maintenance-for-remote-field-devices/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Predictive%20Maintenance%20for%20remote%20field%20devices.md#task-4-create-notification-service-in-microsoft-power-automate): While configuring the flow,  it is mentioned to select the trigger **Delete message** which is  is updated to **Delete message (V2) (preview)** as shown in the below Image. 

Both instruction and screenshot has to be updated.

![LAB74](https://user-images.githubusercontent.com/83349665/125246805-e28f7880-e30f-11eb-9e46-f5cb843df1d6.png)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #24
