### ISSUE TITLE
Master -> Main default branch name update

### ISSUE THREAD

**Issue by sadukie** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#31]
@DawnmarieDesJardins @timahenning 

In order for this repo to be updated from `master` to `main`, we need to:

- Update BHOL, Task 1, Step 3.
- Update BHOL Task 5, Step 2.
- Update HOL, Task 2, Step 1.
- Update HOL, Task 2, Step 2,
- Update HOL, Task 6, Step 1.

These are just text updates. It looks like no images are impacted.

Making note of these here. Currently working on the test/fix.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #32
