### ISSUE TITLE
Update from .NET Core 3.1 to .NET 6.0

### ISSUE THREAD

**Issue by sadukie** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#33]
.NET Core 3.1 will be no longer supported as of December 3, 2022 according to the [Microsoft .NET and .NET Core lifecycle policy](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core).

The applications used in this MCW currently use .NET Core 3.1 and need to be updated.

As .NET 5.0 will no longer be supported as of May 8, 2022, it is recommended to upgrade these applications to use .NET 6.0.

**Comment by DawnmarieDesJardins** [comment]
Labeling as an enhancement for the next scheduled update.
