### ISSUE TITLE
Exercise 2 :Task 3

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#6]
Hi @DawnmarieDesJardins 

In exercise 2 Task 3 ,when I debug the project in Visual studio code Dot net simulator is not showing up ,I'm getting the following message due to .net version issue.
![image](https://user-images.githubusercontent.com/55180169/69879995-da2b2b00-12ee-11ea-959c-ece1eaa6c59a.png)
Can you please specify the exact version for .Net core 2.2 to be used  as it has multiple sub versions.
![image](https://user-images.githubusercontent.com/55180169/69880057-034bbb80-12ef-11ea-8ab2-641d86931f1a.png)

**Comment by joelhulen** [comment]
@srushti-714 I am working on the test/fix for this MCW right now. I'll make this change in the guide.
