### ISSUE TITLE
Exercise 5 TASK 1 STEP 7

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#8]
Hi,

In the exercise 5 task 1 step 7 ,Wrong step is mentioned for the configuration of event hub .
Please find the attachment 

![image](https://user-images.githubusercontent.com/55180169/71177674-84fd8c00-2292-11ea-8dc3-7276605068ca.png)

Thank you

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

Having specific lab section references and screenshots will help expedite support. We will review your issue soon.

Tim
