### ISSUE TITLE
Confusion on .Net core version 

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Predictive-Maintenance-for-remote-field-devices#9]
Hi,

In the Before HOL requirements it is mentioned as we need .net core 2.2 to perform the lab but in the lab files the code is written for netcoreapp 3.0

![image](https://user-images.githubusercontent.com/55180169/71178163-95facd00-2293-11ea-8420-00ae3d3e156a.png)

Can you please verify  whether we need to use two dotnet SDK's for debugging two different projects i.e "FieldDeviceSimulator" requires  .netcore  3.1 and "FailurePredictionFunction" requires .netcore 2.2

![image](https://user-images.githubusercontent.com/55180169/71178401-21745e00-2294-11ea-9ba1-8bf98527b7bf.png)

Thank you

**Comment by srushti-714** [comment]
Hi,
I'm still facing same issue ,the lab doesn't work with one .net core version alone,it needs two dotnet versions for two different projects i.e
Exercise 2 Task 3 works with .net core 3.1 and Exercise 7 Task 8 with .net core 2.2

**Comment by joelhulen** [comment]
This makes no sense. The .csproj file for the Function App sets the target framework to `netcoreapp3.0`, which is the same as the data generator.

I will update the instructions to download both .NET Core versions for now.
